- composer.json
- composer.lock
Use WordHat directly, rather than our fork, now that needed changes are merged
> Use WordHat Directly

- circle.yml
@greg-1-anderson, @ataylorme I'm just going to merge this because it is causing fails in the build tools plugin
https://circleci.com/gh/pantheon-systems/terminus-build-tools-plugin/392
https://circleci.com/gh/pantheon-ci-bot/build-tools-392/1
> Fixing build:env commands

- .gitignore
- composer.json
- composer.lock
- scripts/composer/ScriptHandler.php
> Install Quicksilver Pushback script

- .gitignore
- composer.json
- composer.lock
- scripts/composer/ScriptHandler.php
This reverts commit 12bba7604fea9be169493db17b1653f7acf0f099.
`files/private/github-secrets.json` is created after Quicksilver Pushback runs
> Revert "Install Quicksilver Pushback script (#19)"

- README.md
This changes allows for a copy/paste of install instructions that will complete without error.
> Update README.md for stability flag

- composer.json
- composer.lock
```
Reading composer.json of pantheon-systems/wordpress-composer (4.8.2)Reading composer.json of pantheon-systems/wordpress-composer (4.8.1)Reading composer.json of pantheon-systems/wordpress-composer (4.8)  Reading composer.json of pantheon-systems/wordpress-composer (4.7.5)Reading composer.json of pantheon-systems/wordpress-composer (4.7.4)Reading …
```
> Update Composer dependencies (2017-09-19)

- composer.json
- composer.lock
- tests/behat/features/admin-login.feature
- tests/behat/features/blogname.feature
> Use WordHat 0.8.0

- composer.lock
```
Reading composer.json of pantheon-systems/wordpress-composer (4.8.3)Reading composer.json of pantheon-systems/wordpress-composer (4.8.2)Reading composer.json of pantheon-systems/wordpress-composer (4.8.1)Reading composer.json of pantheon-systems/wordpress-composer (4.8)  Reading composer.json of pantheon-systems/wordpress-composer (4.7.5)Reading …
```
> Update Composer dependencies (2017-10-31-18-11)

- .circleci/deploy-to-pantheon.sh
- pantheon.yml
See https://github.com/pantheon-systems/drops-6/pull/26
> Update to PHP 7.2. 

- web/wp-config.php
> Remove duplicate slash in WP_SITEURL

- pantheon.yml
- web/private/scripts/composer-install.php
- web/private/scripts/prepare-for-pantheon.php
See https://github.com/pantheon-systems/example-drops-8-composer/issues/184 for reasoning.
> Remove deploy product

- README.md
- composer.lock
Ensure new projects start out with WordPress 5.1.
> CORE-1072: WordPress 5.1

- composer.lock
```
Reading composer.json of pantheon-systems/wordpress-composer (5.2.1)Reading composer.json of pantheon-systems/wordpress-composer (5.2)  Reading composer.json of pantheon-systems/wordpress-composer (5.1.1)Reading composer.json of pantheon-systems/wordpress-composer (5.1)  Reading composer.json of pantheon-systems/wordpress-composer (5.0.3)Reading …
```
> Update Composer dependencies (2019-05-24-16-20)

- composer.lock
```
Reading composer.json of pantheon-systems/wordpress-composer (5.2.2)Reading composer.json of pantheon-systems/wordpress-composer (5.2.1)Reading composer.json of pantheon-systems/wordpress-composer (5.2)  Reading composer.json of pantheon-systems/wordpress-composer (5.1.1)Reading composer.json of pantheon-systems/wordpress-composer (5.1)  Reading …
```
> Update Composer dependencies (2019-06-18-19-37)

- .ci/scripts/03-test
- .circleci/config.yml
Tests passing! No longer a work in progress.
> Update Base Image To Build Tools CI 6.x

- composer.lock
```
                                                      Updating dependencies (including require-dev)
Package operations: 78 installs, 2 updates, 0 removals
- Installing ocramius/package-versions (1.4.0): Downloading (connecting...)Downloading (0%)           Downloading (30%)Downloading (45%)Downloading (75%)Downloading (90%)Downloading (100%)
- Installing squizlabs/php_codesniffer (3.5.0): Loading from cache
- Installing dealerdirect/phpcodesniffer-composer-installer (v0.5.0): Downloading …
```
> Update Composer dependencies (2019-10-14-22-25)

- composer.lock
```
                                                      Updating dependencies (including require-dev)
Package operations: 78 installs, 3 updates, 0 removals
- Installing ocramius/package-versions (1.4.0): Downloading (connecting...)Downloading (0%)           Downloading (30%)Downloading (45%)Downloading (75%)Downloading (90%)Downloading (100%)
- Installing squizlabs/php_codesniffer (3.5.2): Loading from cache
- Installing dealerdirect/phpcodesniffer-composer-installer (v0.5.0): Loading from cache
- Updating …
```
> Update Composer dependencies (2019-11-13-01-53)

- .circleci/config.yml
Fixes potential issues with rsync like the one in https://github.com/pantheon-systems/example-drops-8-composer/issues/401
> Use rsync --links option.

- composer.json
- composer.lock
Remove rvtraveller/qs-composer-installer and update other dependency versions for Compsoer 2 compatibility.
> Composer 2

- web/wp-config.php
> Removing exposed salts

- catalog-info.yml
Automatically generated catalog-info.yml file
> [[SITE-1547] Add catalog-info.yml
